baseURL: "https://szewczyk-jakub.github.io/" 
title: Jakub Szewczyk
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: Polonez Bis
          url: polonezbis/
          weight: 2
#        - name: Courses
#          url: courses/
#          weight: 2
#        - name: Data
 #         url: data/
#          weight: 3 
#        - name: Newsletter
#          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "I am a post-doc at the Institute of Psychology at the Jagiellonian University in Kraków, Poland. I study mechanisms and representations underlying language comprehension. I use EEG, fMRI, deep neural networks and behavioral measures."
    author: "Jakub Szewczyk"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jakub Szewczyk
          subtitle: "I am a post-doc at the <a href=\"https://psychologia.uj.edu.pl/en_GB/\" target=\"_blank\" style=\"color:#8e7bd0\">Institute of Psychology</a> at the Jagiellonian University in Kraków, Poland. Currently, I am funded by the <a href=\"polonezbis/\" target=\"_blank\" style=\"color:#8e7bd0\">Polonez Bis</a> grant from the National Science Centre, Poland.  \n&nbsp;  \n
          I study mechanisms and representations underlying language comprehension. I use EEG, fMRI, deep neural networks and behavioral measures.  \n&nbsp;  \n
          Previously, I worked at the University of Illinois at Urbana-Champaign, Donders Institute for Brain, Cognition and Behaviour, and Max Planck Institute for Psycholinguistics.  \n&nbsp;  \n"
          imageUrl: "MPI photo cropped.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jakub Szewczyk
          buttons:
            - name: Projects
              url: projects/
            - name: Papers
              url: papers/
#            - name: Courses
#              url: courses/
#            - name: Data
#              url: data/
#            - name: Newsletter
#              url: https://pmichaillat.substack.com
#            - name: Tags
#              url: tags/
            - name: Polonez Bis
              url: polonezbis/
            - name: Archive
              url: archive/
    socialIcons:
#        - name: CV
#          url: cv.pdf
        - name: Email
          url: mailto:jakub.szewczyk@gmail.com
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=C6Yltn8AAAAJ
#        - name: YouTube
#          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/themeo
#        - name: Substack
#          url: https://pmichaillat.substack.com
        - name: Twitter
          url: https://twitter.com/jkbszwczk

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jakub Szewczyk"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
